# Generated by Django 5.1 on 2024-10-18 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course', '0006_remove_course_select_institute_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('timing', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_students', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_image', models.ImageField(blank=True, max_length=250, null=True, upload_to='student_photos/')),
                ('student_signature', models.ImageField(blank=True, max_length=250, null=True, upload_to='student_signatures/')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('abbreviation', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('select_one', models.CharField(blank=True, choices=[('S/O', 'S/O'), ('D/O', 'D/O'), ('W/O', 'W/O')], max_length=10)),
                ('father_husband_name', models.CharField(blank=True, max_length=100)),
                ('show_father_husband_on_certificate', models.BooleanField(default=False)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('show_surname_on_certificate', models.BooleanField(default=False)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('alternative_contact', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('permanent_address', models.TextField(blank=True)),
                ('exam_type', models.CharField(blank=True, choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=100)),
                ('referral_name', models.CharField(blank=True, max_length=50)),
                ('referral_code', models.CharField(blank=True, max_length=50)),
                ('aadhar_card_number', models.CharField(blank=True, max_length=12)),
                ('caste', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST'), ('Others', 'Others')], max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('remaining_seats_for_batch', models.PositiveIntegerField(blank=True, null=True)),
                ('display_admission_form_id_card_fees_recipt', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10)),
                ('status', models.CharField(default='active', max_length=10)),
                ('course_fees', models.FloatField(blank=True, max_length=100, null=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('discount_rate', models.CharField(blank=True, choices=[('amount-', 'Amount -'), ('percent-', 'Percent -')], default='amount-', max_length=10)),
                ('discount_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_fees', models.FloatField(blank=True, default=0.0, editable=False, null=True)),
                ('fees_received', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('deletion_requested', models.BooleanField(default=False)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('course_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_name', models.CharField(max_length=100)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
