# Generated by Django 5.0.7 on 2024-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discount_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discount_rate',
            field=models.CharField(blank=True, choices=[('amount-', 'Amount -'), ('amount+', 'Amount +'), ('percent-', 'Percent -'), ('percent+', 'Percent +')], default='amount-', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_fees',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
    ]
