# Generated by Django 5.1 on 2024-10-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
