# Generated by Django 5.0.7 on 2024-09-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_discount_type_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_fees',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discount_rate',
            field=models.CharField(blank=True, choices=[('amount-', 'Amount -'), ('percent-', 'Percent -')], default='amount-', max_length=10),
        ),
    ]
