# Generated by Django 5.1.3 on 2024-11-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_course_syllabus_and_more'),
        ('users', '0003_user_username_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='course.course'),
        ),
    ]
