# Generated by Django 5.0.7 on 2024-09-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_course_fees_alter_user_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
