# Generated by Django 5.0.7 on 2024-10-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_batch_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_surname_on_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
