# Generated by Django 5.0.7 on 2025-01-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_video_links',
        ),
    ]
