# Generated by Django 5.0.7 on 2024-07-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_deletion_requested_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deletion_requested_at',
            new_name='deletion_date',
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
