# Generated by Django 5.0.7 on 2024-09-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
