# Generated by Django 5.1.3 on 2024-12-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_token_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_created_at',
        ),
    ]
