# Generated by Django 5.1 on 2024-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_readmission_remarks_alter_user_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('demand draft', 'Demand Draft'), ('online transfer', 'Online Transfer'), ('account adjustment', 'Account Adjustment')], max_length=20, null=True),
        ),
    ]
