# Generated by Django 5.0.7 on 2024-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_batch_exam_batch_exam_course_and_more'),
        ('users', '0007_remove_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='course.course'),
        ),
    ]
