# Generated by Django 5.0.7 on 2024-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_support_email_alter_support_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
    ]
