# Generated by Django 5.0.7 on 2024-11-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payment_date'),
        ('users', '0008_user_is_admitted'),
    ]

    operations = [
    ]
