# Generated by Django 5.0.7 on 2024-12-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='readmission',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='readmission',
            name='course',
        ),
        migrations.RemoveField(
            model_name='readmission',
            name='student',
        ),
        migrations.DeleteModel(
            name='ReferralSettings',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='ReAdmission',
        ),
    ]
