INSERT INTO product_products (
    id,
    uid,
    name,
    brand,
    product_short_description,
    product_long_description,
    trending,
    show_as_new,
    category_id,
    image,
    product_type,
    sku_no
  )
VALUES (
    'id:bigint',
    'uid:character varying',
    'name:character varying',
    'brand:character varying',
    'product_short_description:text',
    'product_long_description:text',
    'trending:character varying',
    'show_as_new:character varying',
    'category_id:bigint',
    'image:character varying',
    'product_type:character varying',
    'sku_no:character varying'
  );INSERT INTO users_user (
    id,
    last_login,
    full_name,
    email,
    password,
    contact,
    is_active,
    is_superuser,
    is_staff,
    address,
    wallet,
    token,
    meta_data,
    profile_pic,
    deletion_date,
    deletion_requested
  )
VALUES (
    'id:bigint',
    'last_login:timestamp with time zone',
    'full_name:character varying',
    'email:character varying',
    'password:text',
    'contact:character varying',
    is_active:boolean,
    is_superuser:boolean,
    is_staff:boolean,
    'address:jsonb',
    'wallet:double precision',
    'token:character varying',
    'meta_data:jsonb',
    'profile_pic:character varying',
    'deletion_date:timestamp with time zone',
    deletion_requested:boolean
  );