# Generated by Django 5.0.7 on 2024-07-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('hide', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('sq_no', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('product_max_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_discount_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_short_description', models.TextField(blank=True, null=True)),
                ('product_long_description', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, default=1, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('trending', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
                ('show_as_new', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
                ('display_as_bestseller', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
        ),
    ]
