# Generated by Django 5.0.7 on 2024-08-12 18:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_long_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
