# Generated by Django 5.0.7 on 2024-08-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
