# Generated by Django 5.0.7 on 2024-08-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='available',
        ),
        migrations.RemoveField(
            model_name='products',
            name='display_as_bestseller',
        ),
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_discount_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_max_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sq_no',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple Product'), ('variant', 'Variant Product')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='sku_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SimpleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_max_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_discount_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('stock', models.IntegerField(blank=True, default=1, null=True)),
                ('product_sku_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_products', to='product.products', to_field='sku_no')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField(blank=True, null=True)),
                ('videos', models.FileField(blank=True, null=True, upload_to='product_videos/')),
                ('simple_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='product.simpleproduct')),
            ],
        ),
    ]
