# Generated by Django 5.0.7 on 2024-08-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_product_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
