# Generated by Django 5.0.7 on 2024-08-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
