# Generated by Django 4.2 on 2024-08-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_products_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='videos',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
