# Generated by Django 5.0.7 on 2024-08-16 06:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.015'), max_digits=5),
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='delivery_charge_per_bag',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='delivery_free_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.015'), max_digits=5),
        ),
    ]
