# Generated by Django 5.0.7 on 2024-08-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_simpleproduct_cgst_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleproduct',
            name='delivery_charge_per_bag',
        ),
        migrations.RemoveField(
            model_name='simpleproduct',
            name='delivery_free_order_amount',
        ),
    ]
