# Generated by Django 5.0.7 on 2024-08-17 07:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_simpleproduct_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
    ]
