# Generated by Django 5.0.7 on 2024-08-19 06:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_simpleproduct_cgst_rate_simpleproduct_sgst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleproduct',
            name='gst_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('3.00'), max_digits=5),
        ),
    ]
