# Generated by Django 5.0.7 on 2024-08-19 06:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_simpleproduct_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleproduct',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='simpleproduct',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='simpleproduct',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
    ]
