# Generated by Django 5.0.7 on 2024-08-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_simpleproduct_cgst_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleproduct',
            name='cgst_rate',
        ),
        migrations.RemoveField(
            model_name='simpleproduct',
            name='sgst_rate',
        ),
    ]
