# Generated by Django 5.0.7 on 2024-08-19 07:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_simpleproduct_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleproduct',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
    ]
