# Generated by Django 5.0.7 on 2024-08-21 15:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_simpleproduct_cgst_simpleproduct_sgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleproduct',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='simpleproduct',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='simpleproduct',
            name='sgst',
        ),
        migrations.AddField(
            model_name='products',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
    ]
