# Generated by Django 5.0.7 on 2024-08-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_products_cgst_amount_products_gst_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gst_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sgst_amount',
        ),
    ]
