# Generated by Django 5.0.7 on 2024-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_deliverysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='flat_delivery_fee',
            field=models.BooleanField(default=False),
        ),
    ]
