# Generated by Django 5.0.7 on 2024-08-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_simpleproduct_flat_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='virtual_product',
            field=models.BooleanField(default=False),
        ),
    ]
