# Generated by Django 5.0.7 on 2024-12-19 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_subject', models.JSONField(blank=True, default=list, null=True)),
                ('course_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_mrp', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('minimum_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_video_link_1', models.URLField(blank=True, null=True)),
                ('course_video_link_2', models.URLField(blank=True, null=True)),
                ('course_syllabus', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('pdf_files', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('course_video_links', models.JSONField(blank=True, default=list, null=True)),
                ('display_course_fees_on_website', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.awardcategory')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(blank=True, default='exam', max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(help_text='Enter the duration in HH:MM:SS format')),
                ('total_marks', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField(blank=True, help_text='Enter the total number of questions', null=True)),
                ('passing_marks', models.PositiveIntegerField(blank=True, help_text='Enter the minimum passing marks', null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('appeared', 'Appeared'), ('postponed', 'Postponed'), ('cancel', 'Cancel')], max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.course')),
            ],
            options={
                'verbose_name': 'Exam Status',
                'verbose_name_plural': 'Exam Statuses',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_theory_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_practical_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('total_mark', models.FloatField(default=0)),
                ('obtained_mark', models.FloatField(blank=True, default=0, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('result', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=7)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('subjects_data', models.JSONField(default=list)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
