# Generated by Django 5.0.7 on 2024-09-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('course_subject', models.CharField(default='', max_length=200)),
                ('course_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_duration', models.CharField(max_length=100)),
                ('exam_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course_video_link_1', models.URLField(blank=True, null=True)),
                ('course_video_link_2', models.URLField(blank=True, null=True)),
                ('course_syllabus', models.TextField()),
                ('eligibility', models.TextField()),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('pdf_files', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('course_video_links', models.JSONField(blank=True, default=list, null=True)),
                ('display_course_fees_on_website', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.awardcategory')),
                ('select_institute_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.instituteplan')),
            ],
        ),
    ]
