# Generated by Django 5.1 on 2024-11-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='subjects_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='obtained_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_mark',
            field=models.FloatField(),
        ),
    ]
