# Generated by Django 5.0.7 on 2024-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_rate',
            field=models.CharField(blank=True, choices=[('amount-', 'Amount -'), ('amount+', 'Amount +'), ('percent-', 'Percent -'), ('percent+', 'Percent +')], default='amount-', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='fees_received',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_fees',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
    ]
