# Generated by Django 5.0.7 on 2024-09-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_balance_course_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fees_received',
        ),
        migrations.RemoveField(
            model_name='course',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_fees',
        ),
    ]
