# Generated by Django 5.1 on 2024-11-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_examresult_subjects_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='practical_marks',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='theory_marks',
        ),
        migrations.AddField(
            model_name='examresult',
            name='obtained_practical_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='obtained_theory_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='obtained_mark',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='result',
            field=models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=7),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_mark',
            field=models.FloatField(default=0),
        ),
    ]
