# Generated by Django 5.1 on 2024-11-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_examresult_practical_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
