# Generated by Django 5.1.3 on 2024-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_examresult_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_syllabus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
