# Generated by Django 5.0.7 on 2024-09-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_balance_remove_course_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='select_institute_plan',
        ),
        migrations.DeleteModel(
            name='InstitutePlan',
        ),
    ]
