# Generated by Django 5.1.3 on 2024-12-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_course_syllabus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
    ]
