# Generated by Django 5.1.3 on 2024-12-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_examresult_marksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='marksheet',
        ),
    ]
