# Generated by Django 5.1 on 2024-10-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_select_institute_plan_and_more'),
        ('users', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
        ),
    ]
