# Generated by Django 5.1 on 2024-10-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_subject',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
