# Generated by Django 5.0.7 on 2024-12-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_examresult_grade'),
        ('users', '0006_remove_user_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
        ),
    ]
