# Generated by Django 5.0.7 on 2024-12-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_exam_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='batch',
        ),
    ]
