# Generated by Django 5.1 on 2024-10-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
