# Generated by Django 5.0.7 on 2024-12-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_exam_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='course',
        ),
    ]
