# Generated by Django 5.1 on 2024-10-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_subject',
            field=models.JSONField(),
        ),
    ]
