# Generated by Django 5.1 on 2024-10-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_course_subject_alter_course_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_subject',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
