# Generated by Django 5.1 on 2024-10-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
