# Generated by Django 5.1 on 2024-10-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_course_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_subject',
            new_name='course_subjects',
        ),
    ]
