# Generated by Django 5.1 on 2024-10-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_course_subject_course_course_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='award',
        ),
    ]
