# Generated by Django 5.1.1 on 2024-11-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='exam_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
    ]
