# Generated by Django 5.1.1 on 2024-11-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_rename_name_exam_exam_name_remove_exam_exam_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam Status', 'verbose_name_plural': 'Exam Statuses'},
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('appear', 'Appear')], default='pending', max_length=10),
        ),
    ]
