# Generated by Django 5.1.1 on 2024-11-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_student_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('appear', 'Appear')], max_length=10),
        ),
    ]
