# Generated by Django 5.0.7 on 2024-08-23 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_attributes', models.JSONField(default=dict)),
                ('product_max_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_discount_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('stock', models.IntegerField(blank=True, default=1, null=True)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.products')),
            ],
        ),
    ]
