# Generated by Django 5.0.7 on 2024-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='status',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
