# Generated by Django 5.0.7 on 2024-11-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requested',
            name='batch',
        ),
    ]
