# Generated by Django 5.0.7 on 2024-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_remove_requested_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedcertificate',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
