# Generated by Django 5.0.7 on 2024-11-25 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_approvedcertificate_certificate_no'),
        ('users', '0002_auto_20241115_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
        ),
    ]
