# Generated by Django 5.0.7 on 2024-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
